config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :activities
  
  root 'welcome#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user

    
    validates :activity_name, presence: true
    validates :date, presence: true
    validates :duration, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @activities = Activity.where(:user_id => current_user.id)
    end
    
    def show
        obj =  Activity.find(params[:id])
        if current_user.id == obj.user_id
            @activity = Activity.find(params[:id])
        else
            #redirect_to activity_path
            #render plain: "Page not found"
            render file: "#{Rails.root}/public/404.html" , status: 404
        end
    end
    
    def new
        @activity = Activity.new
    end

    def edit
        @activity = Activity.find(params[:id])
    end

    def destroy
        @activity = Activity.find(params[:id])
        if @activity.destroy
            #flash[:success] = 'Activity was successfully deleted.'
            redirect_to activities_path
        else
            #flash[:error] = 'Something went wrong'
            redirect_to activities_path
        end
    end
    


    def create
        @activity = Activity.new(activity_params)
        @activity.user = current_user

        if @activity.save
           redirect_to @activity
        else
           render 'new'
        end
    end
    def update
        @activity = Activity.find(params[:id])

        if @activity.update(activity_params)
          flash[:success] = "Object was successfully updated"
          redirect_to @activity
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
    private 
        def activity_params
            params.require(:activity).permit(:activity_name, :date, :duration)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/edit.html.erb
 <div class="mt-5 d-flex justify-content-center"> 
  <div class="">
  
  <h1>Edit</h1>

  <%= form_with(model: @activity,local: true) do |form| %>

  <% if @activity.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@activity.errors.count, "error") %> prohibited
          this activity from being saved:
        </h2>
        <ul>
          <% @activity.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="mt-3">
          <%= form.label :Activity %><br>
          <%= form.select :activity_name, ['Running', 'Swimming', 'Cycling','Walking','Strength Training', 'Rowing', 'Hiking', 'Mountain Biking', 'Skating', 'Skiing', 'Canoeing'] %>
      </div>

      <div class="mt-3">
          <%= form.label :Date %><br>
          <%= form.date_field :date, :class => 'input w-100' %>
      </div>

      <div class="mt-3">
          <%= form.label :Duration %><br>
          <%= form.text_field :duration, :class => 'input w-100'%>
      </div>
      
      <div class="mt-3">
           <%= form.submit "Submit", :class => 'btn sign-up-btn text-white' %>
      </div>
  <% end %>
  <div class="mt-3"> 
    <p><%= link_to 'Back', activities_path %></p>
  </div>
  
</div>
</div>
      <div class="footer bg-color center sec-color px-3 bottom mt-3">
        <div>
              <%# <p>Made by @tejumade</p> %>
            <% if user_signed_in? %>
                <p class="d-inline"><%= current_user.email %></p>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link hover-border-b' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link hover-border-b'  %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link hover-border-b'  %>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link hover-border-b'  %>
            <% end %>
        </div>
        <p> Made with ♡ by tejumade</p>
        </div>

app/views/activities/index.html.erb
<div class="pt-5 bg-color"> 
    <div>
        <div class="">
            <h1 class="text-center">Activities</h1>
            <p class="pl-3"><%= link_to 'New', new_activity_path %></p>
        </div>
        

        <div class="d-md-flex flex-wrap justify-content-center px-3 ">
            <% @activities.each do |activity| %>
                <div class="activity card text-black mr-md-3 w-md-25 mt-3 px-3 pb-3">
                    <div class="img center py-3">
                        <%= image_tag(activity.activity_name + '.svg', :class => 'w-25' )  %>
                    </div>
                    <div class="">
                        <h4><%= activity.activity_name %></h4>
                        <p><%= activity.date %></p>
                    </div>
                    <div class="d-flex justify-content-end">
                        <%= link_to '>>>', activity_path(activity), :class => 'text-black' %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>        
</div>
      <div class=" bg-color center sec-color px-3 py-5">
        <div>
              <%# <p>Made by @tejumade</p> %>
            <% if user_signed_in? %>
                <p class="d-inline"><%= current_user.email %></p>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link hover-border-b' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link hover-border-b'  %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link hover-border-b'  %>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link hover-border-b'  %>
            <% end %>
        </div>
        <p> Made with ♡ by tejumade</p>
        </div>

app/views/activities/new.html.erb
<div class="mt-5 d-flex justify-content-center"> 
  <div class="">
  
  <h1>New Activity</h1>

  <%= form_with scope: :activity, url: activities_path, local: true do |form| %>

  <% if @activity.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@activity.errors.count, "error") %> prohibited
          this activity from being saved:
        </h2>
        <ul>
          <% @activity.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="mt-3">
          <%= form.label :Activity %><br>
          <%= form.select :activity_name, ['Running', 'Swimming', 'Cycling','Walking','Strength Training', 'Rowing', 'Hiking', 'Mountain Biking', 'Skating', 'Skiing', 'Canoeing'] %>
      </div>

      <div class="mt-3">
          <%= form.label :Date %><br>
          <%= form.date_field :date, :class => 'input w-100' %>
      </div>

      <div class="mt-3">
          <%= form.label :Duration %><br>
          <%= form.text_field :duration, :class => 'input w-100'%>
      </div>
      
      <div class="mt-3">
           <%= form.submit "Create", :class => 'btn sign-up-btn text-white' %>
      </div>
  <% end %>
  <div class="mt-3"> 
    <p><%= link_to 'Back', activities_path %></p>
  </div>
  
</div>
</div>

app/views/activities/show.html.erb
<div class="pt-5"> 
    <%# <div class="center">
        <h1>My Activity</h1>
    </div> %>
    <div class="d-md-flex justify-content-center">
    
    
    <div class=" px-3">
        <div class="w-30">
              
                <div class="center mb-3">
                    <%= image_tag(@activity.activity_name + '.svg', :class => 'w-25' )  %>
                </div>
                <div class="d-flex">
                    <strong>ACTIVITY :</strong>
                    <p class="ml-2"><%= @activity.activity_name %></p>
                </div>

                <div class="d-flex">
                    <strong>DATE :</strong>
                    <p class="ml-2"><%= @activity.date %></p>
                </div>

                <div class="d-flex">
                    <strong>DURATION :</strong>
                    <p class="ml-2"><%= @activity.duration %></p>
                </div>

            </div>
    <div>
   
    
    <div class="d-flex">
        <%# change delete to an icon %>
        <p><%= link_to 'Delete', activity_path(@activity),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></p>
        <p class="ml-3"><%= link_to 'Edit', edit_activity_path(@activity) %></p>
        <p class="ml-3"><%= link_to 'Back', activities_path %></p>

    </div>


    </div>
    
     
</div>


 <div class="footer bg-color center sec-color px-sm-3 bottom py-3">
        <div>
              <%# <p>Made by @tejumade</p> %>
            <% if user_signed_in? %>
                <p class="d-inline"><%= current_user.email %></p>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link hover-border-b' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link hover-border-b'  %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link hover-border-b'  %>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link hover-border-b'  %>
            <% end %>
        </div>
        </div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoveAndGroove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body class="h-100">
    <div class="h-100">

  <nav class="navbar navbar-expand-lg justify-content-between bg-color px-3 navbar-light"> 
        <%= link_to 'Move and Groove', root_path, :class => 'text-white' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
              <span class="navbar-toggler-icon"></span>
        </button>
          <div  class="w-md-100">
          
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <% if user_signed_in? %>
                  <p class="nav-item nav-link text-white"><%= current_user.email %></p>
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-item nav-link text-white' %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link text-white'  %>
                <% else %>                  
                  <%= link_to "Sign up", new_user_registration_path, :class => 'nav-item nav-link text-white'  %>
                  <%= link_to "Login", new_user_session_path, :class => 'nav-item nav-link text-white'  %>
                <% end %>

              </ul>
          </div>
          </div>

      </nav> 
       <%= yield %>
    </div>
  </body>     
</html>

app/views/welcome/index.html.erb
<div class="">
    <div class="header px-3  d-flex justify-content-center align-items-center text-white ">
        
            <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4 font-1">Fitness is not a destination its a way of life</h1>
            </div>
            </div>
        
        <div class="buttons">
            <% if user_signed_in? %>
                <button class="btn sign-up-btn text-white px-4 py-3">  <%= link_to "Your Activities", activities_path %></button>
            <% else %>
                <button class="btn sign-up-btn text-white px-4">  <%= link_to "Sign up", new_user_registration_path %></button>
                <button class="btn sign-up-btn text-white px-4">  <%= link_to "Login", new_user_session_path %></button>
            <% end %>
        </div>
    </div>
    <div class="bg-color center sec-color px-sm-3 bottom py-2">
        <div class="mb-2">
              <%# <p>Made by @tejumade</p> %>
            <% if user_signed_in? %>
                <p class="d-inline"><%= current_user.email %></p>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link hover-border-b' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link hover-border-b'  %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link hover-border-b'  %>
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link hover-border-b'  %>
            <% end %>

        </div>
        <p> Made with ♡ by tejumade</p>
        </div>
    <%# links %>
   
    <%# main %>
    <%# <div class="center">
        <h3>Take the leap of faith today</h3>
        <div class="mt-5">
        <h3>Track Your Activities</h3>
        <p>Move and groove allows you to record your activities</p>
        </div>
    </div> %>

</div>